[package]
name = "dialoguemaker/pause-effect"
version = "0.1.0-patch-2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/DialogueMaker/pause-effect"
authors = ["Christian Toney <christian.toney@beastslash.com>"]
include = ["src", "src/**/*.lua", "wally.toml", "default.project.json"]
exclude = ["**"]

[dependencies]
dialogue-content-fitter = "dialoguemaker/dialogue-content-fitter@0.1.0-patch-1"
effect = "dialoguemaker/effect@0.1.0-patch-2"
effect-types = "dialoguemaker/effect-types@0.1.0-patch-3"